In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
dataset1=pd.read_csv("Ecommerce Customers.csv")

In [3]:
dataset1.head()

Email  \
0      mstephenson@fernandez.com   
1              hduke@hotmail.com   
2               pallen@yahoo.com   
3        riverarebecca@gmail.com   
4  mstephens@davidson-herman.com   

                                             Address            Avatar  \
0       835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1     4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2  24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3   1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4  14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

In [4]:
dataset1.drop(["Email","Address","Avatar","Time on Website"],axis=1,inplace=True)

In [5]:
dataset1

Avg. Session Length  Time on App  Length of Membership  \
0              34.497268    12.655651              4.082621   
1              31.926272    11.109461              2.664034   
2              33.000915    11.330278              4.104543   
3              34.305557    13.717514              3.120179   
4              33.330673    12.795189              4.446308   
5              33.871038    12.026925              5.493507   
6              32.021596    11.366348              4.685017   
7              32.739143    12.351959              4.434273   
8              33.987773    13.386235              3.273434   
9              31.936549    11.814128              3.202806   
10             33.992573    13.338975              2.482608   
11             33.879361    11.584783              3.713209   
12             29.532429    10.961298              4.046423   
13             33.190334    12.959226              3.918542   
14             32.387976    13.148726              2.494544   
15             30.737720    12.636606              3.357847   
16             32.125387    11.733862              3.136133   
17             32.338899    12.013195              2.420806   
18             32.187812    14.715388              1.516576   
19             32.617856    13.989593              4.064549   
20             32.912785    11.365492              4.599937   
21             33.503087    12.877984              1.559152   
22             31.531604    13.378563              2.245148   
23             32.903251    11.657576              3.919302   
24             34.507551    12.893670              5.705154   
25             33.029332    11.765813              2.721736   
26             33.541231    12.783892              4.648199   
27             32.335990    13.007819              2.996365   
28             33.110205    11.982045              3.923489   
29             33.105438    11.965020              4.742578   
..                   ...          ...                   ...   
470            32.518197    11.509253              3.022676   
471            34.523020    11.405770              4.041245   
472            33.665990    12.263718              3.139527   
473            31.609840    12.710701              2.562819   
474            33.700886    13.471578              2.379076   
475            33.811733    11.186809              4.301996   
476            34.336677    11.246813              2.094762   
477            31.061325    12.357638              4.089331   
478            33.069768    11.764326              3.516051   
479            34.606242    11.761884              1.820811   
480            34.238242    11.550300              4.183144   
481            32.047815    12.482670              3.393903   
482            30.971676    11.731364              4.426364   
483            33.606851    12.214074              2.905238   
484            33.448125    11.903757              2.782758   
485            33.369381    12.222484              3.447018   
486            33.452295    12.005916              4.712234   
487            32.904692    11.913745              1.228112   
488            35.630854    12.125402              4.019051   
489            32.246350    11.305551              1.707390   
490            34.695591    11.608997              3.163092   
491            34.343922    11.693058              3.447093   
492            33.680937    11.201570              2.208814   
493            32.060914    12.625433              5.412358   
494            33.431097    13.350632              2.768852   
495            33.237660    13.566160              3.746573   
496            34.702529    11.695736              3.576526   
497            32.646777    11.499409              4.958264   
498            33.322501    12.391423              2.336485   
499            33.715981    12.418808              2.735160   

     Yearly Amount Spent  
0             587.951054  
1             392.204933  
2             487

In [6]:
x=dataset1.iloc[:,0:3]
x

Avg. Session Length  Time on App  Length of Membership
0              34.497268    12.655651              4.082621
1              31.926272    11.109461              2.664034
2              33.000915    11.330278              4.104543
3              34.305557    13.717514              3.120179
4              33.330673    12.795189              4.446308
5              33.871038    12.026925              5.493507
6              32.021596    11.366348              4.685017
7              32.739143    12.351959              4.434273
8              33.987773    13.386235              3.273434
9              31.936549    11.814128              3.202806
10             33.992573    13.338975              2.482608
11             33.879361    11.584783              3.713209
12             29.532429    10.961298              4.046423
13             33.190334    12.959226              3.918542
14             32.387976    13.148726              2.494544
15             30.737720    12.636606              3.357847
16             32.125387    11.733862              3.136133
17             32.338899    12.013195              2.420806
18             32.187812    14.715388              1.516576
19             32.617856    13.989593              4.064549
20             32.912785    11.365492              4.599937
21             33.503087    12.877984              1.559152
22             31.531604    13.378563              2.245148
23             32.903251    11.657576              3.919302
24             34.507551    12.893670              5.705154
25             33.029332    11.765813              2.721736
26             33.541231    12.783892              4.648199
27             32.335990    13.007819              2.996365
28             33.110205    11.982045              3.923489
29             33.105438    11.965020              4.742578
..                   ...          ...                   ...
470            32.518197    11.509253              3.022676
471            34.523020    11.405770              4.041245
472            33.665990    12.263718              3.139527
473            31.609840    12.710701              2.562819
474            33.700886    13.471578              2.379076
475            33.811733    11.186809              4.301996
476            34.336677    11.246813              2.094762
477            31.061325    12.357638              4.089331
478            33.069768    11.764326              3.516051
479            34.606242    11.761884              1.820811
480            34.238242    11.550300              4.183144
481            32.047815    12.482670              3.393903
482            30.971676    11.731364              4.426364
483            33.606851    12.214074              2.905238
484            33.448125    11.903757              2.782758
485            33.369381    12.222484              3.447018
486            33.452295    12.005916              4.712234
487            32.904692    11.913745              1.228112
488            35.630854    12.125402              4.019051
489            32.246350    11.305551              1.707390
490            34.695591    11.608997              3.163092
491            34.343922    11.693058              3.447093
492            33.680937    11.201570              2.208814
493            32.060914    12.625433              5.412358
494            33.431097    13.350632              2.768852
495            33.237660    13.566160              3.746573
496            34.702529    11.695736              3.576526
497            32.646777    11.499409              4.958264
498            33.322501    12.391423              2.336485
499            33.715981    12.418808              2.735160

[500 rows x 3 columns]

In [7]:
y=dataset1.iloc[:,3]
y

0      587.951054
1      392.204933
2      487.547505
3      581.852344
4      599.406092
5      637.102448
6      521.572175
7      549.904146
8      570.200409
9      427.199385
10     492.606013
11     522.337405
12     408.640351
13     573.415867
14     470.452733
15     461.780742
16     457.847696
17     407.704548
18     452.315675
19     605.061039
20     534.705744
21     419.938775
22     436.515606
23     519.340989
24     700.917092
25     423.179992
26     619.895640
27     486.838935
28     529.537665
29     554.722084
          ...    
470    424.728774
471    541.049831
472    469.383146
473    444.545550
474    492.556834
475    535.321610
476    408.958336
477    487.555458
478    487.646232
479    402.167122
480    551.023002
481    497.389558
482    494.638610
483    479.247417
484    462.656519
485    515.502480
486    576.477607
487    357.857984
488    597.739879
489    327.377953
490    510.401388
491    510.501478
492    403.819520
493    627.603319
494    510

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
x_train

array([[-1.03415579, -1.34907928, -0.5732489 ],
       [-0.78334247, -0.07054682, -0.03466339],
       [ 1.35248414,  0.18301939,  1.14981557],
       ...,
       [ 0.01150801, -0.32743962,  1.46646745],
       [-0.337729  ,  0.95382088,  0.55720304],
       [ 1.5063598 ,  1.25269647,  1.42967454]])

In [27]:
y_train

107    378.330907
336    478.600916
71     595.822837
474    492.556834
6      521.572175
412    444.053827
113    422.426776
236    501.928265
299    282.471246
155    503.978379
272    582.491924
7      549.904146
137    433.048769
8      570.200409
463    392.285244
432    486.947054
375    478.951405
284    463.591418
210    496.554082
188    524.637965
430    556.186369
49     416.358354
134    407.804031
365    594.274483
413    493.181261
239    538.774933
59     547.365141
406    411.186964
391    503.175085
411    589.026490
          ...    
265    567.475011
72     418.150081
333    498.635598
25     423.179992
165    513.450571
337    440.002748
483    479.247417
174    465.176623
486    576.477607
39     537.846195
193    545.945492
314    610.128033
396    669.987141
88     547.125932
472    469.383146
70     444.966552
87     473.728967
292    584.218313
242    451.628611
277    616.660286
211    548.518529
9      427.199385
359    561.874658
195    424.675281
251    393

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [30]:
y_pred=mlr.predict(x_test)

In [31]:
y_pred

array([438.14048248, 489.87345928, 370.73952859, 514.53747499,
       496.52832827, 451.38517908, 457.92666122, 336.67120119,
       527.86406639, 663.34672423, 559.89926049, 525.97960457,
       552.20324841, 456.99735777, 450.35224906, 432.26932687,
       563.37396342, 408.84417541, 599.57357305, 486.86762327,
       716.21840208, 496.8930287 , 411.58372427, 556.05798645,
       550.83428121, 398.0939475 , 421.18533846, 395.64871305,
       548.02686228, 463.3707458 , 558.56219405, 504.9607563 ,
       505.62827725, 463.91251731, 425.49868576, 400.69207866,
       503.80876315, 430.42712761, 570.14832273, 422.06126143,
       487.64450429, 602.23615523, 615.87419382, 589.03631893,
       449.92546542, 379.85349676, 558.81444107, 463.11734629,
       502.21160324, 401.21309758, 524.60465014, 416.51958597,
       576.48396126, 477.92036001, 457.06180332, 397.57331224,
       564.80176363, 305.25062324, 562.2667309 , 476.93939014,
       498.46729774, 433.99851549, 464.93516564, 577.14

In [32]:
mlr.intercept_

501.165169819684

In [33]:
mlr.coef_

array([24.61721681, 38.33710078, 60.56508472])

In [35]:
x_train.shape

(400, 3)

In [36]:
pre=mlr.predict([[300,3289,5.0]])

In [37]:
pre

array([134279.88010802])

In [38]:
dataset1.corr()

Avg. Session Length  Time on App  Length of Membership  \
Avg. Session Length              1.000000    -0.027826              0.060247   
Time on App                     -0.027826     1.000000              0.029143   
Length of Membership             0.060247     0.029143              1.000000   
Yearly Amount Spent              0.355088     0.499328              0.809084   

                      Yearly Amount Spent  
Avg. Session Length              0.355088  
Time on App                      0.499328  
Length of Membership             0.809084  
Yearly Amount Spent              1.000000

In [39]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9861886860192693